### ISSUE TITLE
the author key is wrong 

### ISSUE THREAD

**Issue by ChenZhiKuan** [graphql-java/tutorials#16]
in schema.graphqls this file,defined property "author",but in GraphQLDataFetchers.java this file,defined property "authorId"

**Comment by dondonz** [comment]
Perhaps you're wondering why the schema has a Book type with an author field, but the Book class itself actually has an authorId. Exactly how you model the data in Java will depend on your data source. In this tutorial example, the Book records contain only the id of an author, rather than the full author information.
